<template>
  <div class="home-bank">
    <!-- <header class="bank-header">
      <span class="name">最热视频</span>
    </header> -->
    <div class="bank-body clearfix">
      <div class="top">
        <div class="banner-warp">
          <div class="banner">
            <router-link :to="/video/ + recom_star.vid">
              <img :src="recom_star.cover" :alt="recom_star.name" />
              <span :title="recom_star.name">{{recom_star.name}}</span>
            </router-link>
          </div>
        </div>
        <div class="subbanner-warp">
          <ul>
            <li class="subbanner" v-for="item in recom_others" :key="item.vid">
              <router-link :to="/video/ + recom_star.vid">
                <img :src="recom_star.cover" :alt="recom_star.name" />
                <span :title="recom_star.name">{{recom_star.name}}</span>
              </router-link>
            </li>
          </ul>
        </div>
      </div>
      <div class="bottom">
        <div class="subbanner" v-for="item in recom_others" :key="item.vid">
          <router-link :to="/video/ + recom_star.vid">
            <img :src="recom_star.cover" :alt="recom_star.name" />
            <span :title="recom_star.name">{{recom_star.name}}</span>
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Middle",
  computed: {
    recom_star() {
      return this.recommends[0];
    },
    recom_others() {
      return [].slice.apply(this.recommends, [1]);
    },
  },
  data() {
    return {
      recommends: [
        {
          vid: 1,
          name: "好康视频",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 2,
          name: "好康视频2",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 3,
          name: "好康视频3",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 4,
          name: "好康视频4",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 5,
          name: "好康视频5",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 6,
          name: "好康视频6",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
        {
          vid: 7,
          name: "好康视频7",
          cover: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgIBwgNBwcHBwcHBw0HBwcHBw8ICQcNFREWFhURFRMYKCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALEBHAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAQC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2oBtKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKAAAAAAAAAAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgKAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAACAoAAAAAAAAACKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAAAioCgAAAAAAAAAAAAAAAIoAAAAAigAAAAAAAAAAAICgAAAAAAAAAAAAAAAAgKAAAAAAAAAAACKAAACKgKAAAAAAAAAAAAAAAAAAAAAAigAAAAAAAAAAAICgAAAAAAAIoAAAAAAACAoAAAAAAAAAAAIoAAAIqAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKAAAIAP/Z",
          url: "www.baidu.com",
        },
      ],
    };
  },
};
</script>

<style scoped>
img {
  display: block;
}

.home-bank {
}

.bank-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 36px;
  margin-bottom: 16px;
}

.bank-body {
}

.name {
  display: inline-block;
  color: #212121;
  vertical-align: bottom;
  font-size: 20px;
  line-height: 28px;
}

.top {
  white-space: nowrap;
}

.banner-warp {
  display: inline-block;
  vertical-align: top;
  height: 256px;
  width: 372px;
  overflow: hidden;
}

.subbanner-warp {
  display: inline-block;
  vertical-align: top;
  width: 567px;
  margin-left: 20px;
  overflow: hidden;
}

.subbanner-warp ul {
  white-space: normal;
}

.subbanner {
  display: inline-block;
  white-space: pre-wrap;
  margin-bottom: 20px;
  margin-right: 20px;
}

.subbanner:nth-of-type(3n) {
  margin-right: 0;
}

.subbanner img {
  height: 90px;
  width: 175px;
}

.subbanner span {
  display: block;
  width: 160px;
  height: 18px;
  line-height: 18px;
  overflow: hidden;
}

.banner img {
  height: 208px;
  width: 400px;
}

.banner span {
  display: block;
  width: 160px;
  height: 18px;
  line-height: 18px;
  overflow: hidden;
}

.bottom {
  float: left;
  overflow: hidden;
}
</style>